# Generated by Django 2.2.5 on 2019-09-05 18:01

from django.db import migrations, models
import django.db.models.deletion
import poker.poker.enums


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face', models.IntegerField(choices=[(poker.poker.enums.Face(2), 2), (poker.poker.enums.Face(3), 3), (poker.poker.enums.Face(4), 4), (poker.poker.enums.Face(5), 5), (poker.poker.enums.Face(6), 6), (poker.poker.enums.Face(7), 7), (poker.poker.enums.Face(8), 8), (poker.poker.enums.Face(9), 9), (poker.poker.enums.Face(10), 10), (poker.poker.enums.Face(11), 11), (poker.poker.enums.Face(12), 12), (poker.poker.enums.Face(13), 13), (poker.poker.enums.Face(14), 14)])),
                ('colour', models.IntegerField(choices=[(poker.poker.enums.Colour(1), 1), (poker.poker.enums.Colour(2), 2), (poker.poker.enums.Colour(3), 3), (poker.poker.enums.Colour(4), 4)])),
                ('hand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='poker.Hand')),
            ],
            options={
                'unique_together': {('hand', 'face', 'colour')},
            },
        ),
    ]
